### PR TITLE
feat: remove team jobs

### PR DESCRIPTION
**Pull request by j-zimnowoda**
This is an old jobs concept that we have already deprecated long time ago.

### CODE REVIEW

**Review by ferruhcihan — DISMISSED** [review]
LGTM

**Comment by j-zimnowoda** [comment]
This cannot be merged because the values migration does not work as expected

**Comment by j-zimnowoda** [comment]
Added functionality to remove files and tested on cluster:
image

From the screenshot you can see that after values migration the jobs related files are removed

**Review by ferruhcihan — APPROVED** [review]
Tested with a cluster, LGTM

**Pull request merged**
