### PR TITLE
feat: node 20 upgrade

### PR DESCRIPTION
**Pull request by CasLubbers**
Updates apl-core to node 20
Updated most of the packages to latest greatest

### CODE REVIEW

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]
According to node docs we should use rpm in version 10
https://nodejs.org/en/about/previous-releases

image

**Review by dennisvankekem — COMMENTED** [review]
Not sure if this is just me, but when I run `npm run server` locally it does start but it also immediately exits which results in apl-api crashing

**Comment by Ani1357** [comment]
Tried updating my existing cluster to this branch but the apl-api keeps crashing. This are the logs:
```
2024-11-18T09:15:24.282Z otomi:app NODE_ENV:  production
2024-11-18T09:15:24.343Z otomi:app Loading api spec from: /app/dist/src/generated-schema.json
2024-11-18T09:15:24.663Z otomi:app Error: connect ECONNREFUSED 127.0.0.1:17771
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
stream closed EOF for otomi/otomi-api-7988dc7bf9-hs6v2 (otomi-api)
```

**Comment by dennisvankekem** [comment]
Fix seems to work, @Ani1357 can you retest on cluster?

**Comment by dennisvankekem** [comment]
@CasLubbers can you adhere to branch naming format next time? e.g [APL-{ticket number}]

**Comment by CasLubbers** [comment]
> @CasLubbers can you adhere to branch naming format next time? e.g [APL-{ticket number}]

Yes will do, created the ticket after I already was working on the branch... also not the way it should go.

**Review by Ani1357 — APPROVED** [review]
Tested by updating my existing cluster.
Tested by creating new team, workload and service. All tests  were successful.

**Review by ferruhcihan — COMMENTED** [review]
I tested with a cluster, it works. However I got some warnings/errors when I run `bootstrap-dev` debugger or `npm run bootstrap-dev`

**Review by ferruhcihan — APPROVED** [review]

**Review by j-zimnowoda — APPROVED** [review]

**Pull request merged**
