### PR TITLE
feat: remove shortcuts

### PR DESCRIPTION
**Pull request by dennisvankekem**
## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

### CODE REVIEW

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]
Please provide migrations in the `values-changes.yaml` file

**Review by ferruhcihan — APPROVED** [review]
LGTM

**Comment by dennisvankekem** [comment]
tested locally. Also, @j-zimnowoda would the way it's noted in `values-changes.yaml` suffice? Or is it worth it to update `migrate.ts` to include an `{app}` wildcard and iterate through it in `unparsePaths` in the case we need to add/remove something from all apps?

**Review by j-zimnowoda — DISMISSED** [review]
Looks good. Just update version in the helmfile.d/snippets/defaults.yaml file to 
```
        version: 24
```

**Pull request merged**
