### PR TITLE
feat: update helm secrets

### PR DESCRIPTION
**Pull request by CasLubbers**
- Updated helm secrets to latest version and fix the breaking changes

### CODE REVIEW

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]
Got an error on upgrade
```
2024-12-10T09:23:31.868Z otomi:common:crypt:decrypt:info Starting decryption
2024-12-10T09:23:32.852Z otomi:common:crypt:decrypt:info Decryption is done
in /home/app/stack/helmfile.tpl/helmfile-dump-all.yaml: failed to read ../helmfile.d/snippets/env.gotmpl: environment values file matching "/home/app/stack/env/env/secrets.settings.yaml.dec" does not exist in "."
2024-12-10T09:23:33.326Z otomi:global:error Error: in /home/app/stack/helmfile.tpl/helmfile-dump-all.yaml: failed to read ../helmfile.d/snippets/env.gotmpl: environment values file matching "/home/app/stack/env/env/secrets.settings.yaml.dec" does not exist in "."
    at hfCore (/home/app/stack/dist/src/common/hf.js:45:30)
    exit code: 1
    at EventEmitter.end (/home/app/stack/node_modules/zx/build/core.cjs:203:26)
    at EventEmitter.emit (node:events:530:35)
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/build/vendor-core.cjs:493:16)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```
It looks like the file was not decrypted

**Review by ferruhcihan — CHANGES_REQUESTED** [review]
I got the below error with `npm run bootstrap-dev` command 
Screenshot 2024-12-10 at 10 35 47

and also got same error when I create a cluster from this branch
Screenshot 2024-12-10 at 10 36 29

I checked the flow and believe the issue is that the encrypted files are not stored with their original filenames. During decryption, the file cannot be decrypted because it is not recognized as an encrypted file. Additionally, it seems that the new version of the helm secrets plugin likely does not follow the creation rules specified in the .sops.yaml file.

**Comment by j-zimnowoda** [comment]
I tried again upgrade on a cluster but this time I get:
```
2024-12-10T19:23:46.025Z otomi:common:crypt:encrypt:info Skipping encryption for env/apps/secrets.gitea.yaml as it has not changed
[helm-secrets] Already encrypted: secrets.cert-manager.yaml
Error: plugin "secrets" exited with error
2024-12-10T19:23:46.106Z otomi:common:crypt:runOnSecretFiles:error Error: [helm-secrets] Already encrypted: secrets.cert-manager.yaml
Error: plugin "secrets" exited with error
    at /home/app/stack/dist/src/common/crypt.js:51:40
    exit code: 1
    at EventEmitter.end (/home/app/stack/node_modules/zx/build/core.cjs:203:26)
    at EventEmitter.emit (node:events:530:35)
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/build/vendor-core.cjs:493:16)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
2024-12-10T19:23:46.108Z otomi:global:error Error: [helm-secrets] Already encrypted: secrets.cert-manager.yaml
Error: plugin "secrets" exited with error
    at /home/app/stack/dist/src/common/crypt.js:51:40
    exit code: 1
    at EventEmitter.end (/home/app/stack/node_modules/zx/build/core.cjs:203:26)
    at EventEmitter.emit (node:events:530:35)
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/build/vendor-core.cjs:493:16)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)

```

**Comment by j-zimnowoda** [comment]
Tried again. the upgrade went smooth. Unfortunately adding a new team failed miserable :(
```
2024-12-11T14:08:15.385Z otomi:server:log Request to prepare values repo
2024-12-11T14:08:15.387Z otomi:cmd:bootstrap:genSops:log Creating sops file for provider age
2024-12-11T14:08:15.397Z otomi:cmd:bootstrap:genSops:log Ready generating sops files. The configuration is written to: /tmp/otomi/values/jzimnowo@apl.local/.sops.yaml
2024-12-11T14:08:15.398Z otomi:cmd:bootstrap:genSops:info Copying sops related files
2024-12-11T14:08:15.398Z otomi:common:crypt:encrypt:info Starting encryption
2024-12-11T14:08:15.400Z otomi:common:crypt:preCrypt:warn Expecting /tmp/otomi/values/jzimnowo@apl.local/.secrets to exist and hold credentials for SOPS. Not needed if already exists in env.
2024-12-11T14:08:15.402Z otomi:common:crypt:encrypt:info Skipping encryption for env/apps/secrets.cert-manager.yaml as it has not changed
2024-12-11T14:08:15.402Z otomi:common:crypt:encrypt:info Skipping encryption for env/apps/secrets.drone.yaml as it has not changed
2024-12-11T14:08:15.403Z otomi:common:crypt:encrypt:info Skipping encryption for env/apps/secrets.gitea.yaml as it has not changed
2024-12-11T14:08:15.403Z otomi:common:crypt:encrypt:info Skipping encryption for env/apps/secrets.harbor.yaml as it has not changed
2024-12-11T14:08:15.403Z otomi:common:crypt:encrypt:info Skipping encryption for env/apps/secrets.keycloak.yaml as it has not changed
2024-12-11T14:08:15.404Z otomi:common:crypt:encrypt:info Skipping encryption for env/apps/secrets.loki.yaml as it has not changed
2024-12-11T14:08:15.404Z otomi:common:crypt:encrypt:info Skipping encryption for env/apps/secrets.oauth2-proxy-redis.yaml as it has not changed
2024-12-11T14:08:15.404Z otomi:common:crypt:encrypt:info Skipping encryption for env/apps/secrets.oauth2-proxy.yaml as it has not changed
2024-12-11T14:08:15.404Z otomi:common:crypt:encrypt:info Skipping encryption for env/secrets.settings.yaml as it has not changed
2024-12-11T14:08:15.404Z otomi:common:crypt:encrypt:info Encrypting env/secrets.teams.yaml, time difference was 4 seconds
[helm-secrets] Already encrypted: secrets.teams.yaml
Error: plugin "secrets" exited with error
2024-12-11T14:08:15.460Z otomi:common:crypt:runOnSecretFiles:error Error: [helm-secrets] Already encrypted: secrets.teams.yaml
Error: plugin "secrets" exited with error
    at /home/app/stack/dist/src/common/crypt.js:51:40
    exit code: 1
    at EventEmitter.end (/home/app/stack/node_modules/zx/build/core.cjs:203:26)
    at EventEmitter.emit (node:events:530:35)
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/build/vendor-core.cjs:493:16)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
2024-12-11T14:08:15.461Z otomi:server:error [helm-secrets] Already encrypted: secrets.teams.yaml
Error: plugin "secrets" exited with error

```

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]
could you read my last comment?

**Comment by CasLubbers** [comment]
Should work now with newest commit

**Review by j-zimnowoda — APPROVED** [review]

**Review by ferruhcihan — APPROVED** [review]
Hard work! LGTM, tested 👍🏻

**Pull request merged**
